### ISSUE TITLE
Determining scope from ADA recommendations

### ISSUE THREAD

**Issue by monicatduque** [johnnybender/adastandards2017#16]
When determining scope from the Excel sheet ADA recommendations, we decided to try to find some guidance via Google. This brought us to the actual ADA Diabetes Care website, which outlines criteria for the exact recommendations we have. 

For example, rec008 is "Screening for prediabetes and risk for future diabetes with an informal assessment of risk factors or validated tools should be considered in asymptomatic adults. B" On this ADA Diabetes Care criteria, it outlines the following:

1. Testing should be considered in overweight or obese (BMI ≥25 kg/m2 or ≥23 kg/m2 in Asian Americans) adults who have one or more of the following risk factors:
A1C ≥5.7% (39 mmol/mol), IGT, or IFG on previous testing

 • first-degree relative with diabetes
 • high-risk race/ethnicity (e.g., African American, Latino, Native American, Asian American, Pacific Islander)
 • women who were diagnosed with GDM
 • history of CVD
 • hypertension (≥140/90 mmHg or on therapy for hypertension)
 • HDL cholesterol level <35 mg/dL (0.90 mmol/L) and/or a triglyceride level >250 mg/dL (2.82 mmol/L)
 • women with polycystic ovary syndrome
 • physical inactivity
 • other clinical conditions associated with insulin resistance (e.g., severe obesity, acanthosis nigricans).
2. For all patients, testing should begin at age 45 years.
3. If results are normal, testing should be repeated at a minimum of 3-year intervals, with consideration of more frequent testing depending on initial results (e.g., those with prediabetes should be tested yearly) and risk status.

Is this the scope we should use when setting up the Boolean logic in Wellcentive or are we thinking WAY to in depth? The Excel sheet says "All patients with diabetes" so it could simply just be using the same DiabeticModule that we created earlier, which includes a general scope of all patients with diabetes. 

Thanks for the guidance!

**Comment by johnnybender** [comment]
Hope I helped answer the question! https://github.com/Edward-Yao31/adastandards2016
